### ISSUE TITLE
Ssh login

### ISSUE THREAD

**Issue by GregoryWest501** [project-owner/Peppy#10]
what is the user id and pw to login to the tty interface of havusai version of Peppy?   Tried everything i can think of.

**Comment by project-owner** [comment]
Hi,

The user is always:
pi
the password is the edition name. For example for the latest Hiroshige Edition the password is:
Hiroshige
for the previous Hokusai Edition the password is:
Hokusai

Best regards

**Comment by project-owner** [comment]
The answer provided

**Comment by GregoryWest501** [comment]
Works now!!!   Thanks
