### ISSUE TITLE
Odd issue with audio output.

### ISSUE THREAD

**Issue by GregoryWest501** [project-owner/Peppy#11]
I installed hokusai-waveshare.5.0 on my PI 3b.   I have the 5" display attached and the speakers are connected the the PI 3.5mm audio jack and everything works as expected.    When I tried out hiroshige-waveshare.5.0 on the same PI, and in the exact same config, there is no sound at all.   Can anyone shed some like on this and how I might get this to work.

**Comment by project-owner** [comment]
I've found some issues related to the touchscreen events. I described the fix here:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Known-Issues
I will update the disk images soon.
But that should not affect the audio output.

**Comment by GregoryWest501** [comment]
OK after much testing I have narrowed it down a little.   Everything seems to work OK until I set up the screen saver.  For one thing would like the weather here in Winnipeg, and not in Washington DC.  Not sure if that gives you any clues.    Will try and narrow down what in the screen saver causes the sound to go away.

**Comment by GregoryWest501** [comment]
I change the weather info via Web UI.  Trying the new IMG file now.   Will check the weather config file too.   And upload it here is need be.    Another interesting thing, as the screen savers go by the VU meters are not registering anything.  As if nothing is playing.

**Comment by project-owner** [comment]
Some online radio stations or files provide very low signal level which is not enough for VU Meter. Try to switch to another station or file.

If you will still see the issue with audio please try to run the ' sudo raspi-config' command from the terminal and make sure that 'Headphones' (not HDMI) is selected in the menu /System Options/Audio.

**Comment by GregoryWest501** [comment]
Upgraded to current release, everything seems to be working fine now!

⁣Get BlueMail for Android ​
