### ISSUE TITLE
Hiroshige bluetooth problem

### ISSUE THREAD

**Issue by pentomas** [project-owner/Peppy#12]
Hello,

when I install the Hiroshige Peepy edition from an image or according to the expert procedure with a 3.5 touch screen, bluetooth does not work - for a step before installing the touch screen, it's fine, but then it goes wrong.
Network setup ends with freezing ...

in ssh shell:
sudo bluetoothctl is frozen

The Hokusai edition is ok.

I ask for some advice. well thank you

RPI4 2gb

Peter

**Comment by project-owner** [comment]
Hi Peter, please let me know which display and which disk image you use.

**Comment by pentomas** [comment]
Hi,

1. first I installed a hiroshige-waveshare.3.5 image and I used a WaveShare 3.5 RPI lcd A v3 display - inverted colors but the touch works, unfortunately bluetoth doesn't work

2. then I installed according to the guide - expert - RaspiOS image (March 4th 2021) + the following steps - until the display driver install step the bluetooth was functional ... after this step the bluetooth setup (in ssh and network setup in Peppy) froze. I installed the original driver for Waveshare display (version A) and also the driver from https://github.com/goodtft/LCD-show.git (on a fresh RaspiOS image) - bluetooth not working. (this worked for me in the Hokusai version). I also tried another MHS-3.5 inch display with the original driver - the same result.
It looks like there is a problem with the compatibility of display drivers with the latest version of RRaspiOS.

The Hiroshige headless version has no problem, bluetooth works OK.

Thanks

Peter

**Comment by project-owner** [comment]
Hi Peter,

Probably driver installation stops the bluetooth service.
I would recommend after display driver installation add the following line to the file /etc/rc.local right before the line where Peppy player starts:
```
sudo service bluetooth restart
```
Please let me know if it helps or not.

Here is the discussion about bluetooth issues in Pi 4:
https://www.raspberrypi.org/forums/viewtopic.php?f=140&t=306920&sid=f77579c91cd0995e5e1a516675845e45

Regards

**Comment by pentomas** [comment]
Hi,
no it didn't help ... no change ... I'll keep looking

Thanks

Peter

**Comment by pentomas** [comment]
Hi,
I found a solution:
https://www.raspberrypi.org/forums/viewtopic.php?t=306699

that solved my problem

good luck

Peter
