### ISSUE TITLE
GUI Freeze while on network selection loading screen.

### ISSUE THREAD

**Issue by BOsborneOfficial** [project-owner/Peppy#13]
I self installed on fresh raspbian install on pi 3b and am using integrated WiFi chip. Whenever I try to connect to a new network the GUI freezes on the network 'loading' screen.

**Comment by project-owner** [comment]
Hi, did you follow these instructions?
https://github.com/project-owner/Peppy.doc/wiki/WiFi

Best regards

**Comment by BOsborneOfficial** [comment]
Thank you so much!

**Comment by project-owner** [comment]
I hope it works fine now. Closing the issue.
