### ISSUE TITLE
Stuck lyrics

### ISSUE THREAD

**Issue by onetablespoon** [project-owner/Peppy#18]
My Peppy gets stuck showing lyrics. Nothing short of a reboot can get touch screen control or web interface back. When this happens the lyrics get stuck on a song and do not update even though the stream continues. Thanks.

**Comment by project-owner** [comment]
Hi, does it happen in Radio mode or Audio File mode? If radio, could you tell me which station so that I could try to reproduce the issue.

Thanks!

**Comment by onetablespoon** [comment]
My bad, Duh! Just reread the wiki re: Lyric screen saver. Clicking top of screen gets me out. Thanks project-owner for Peppy!
