### ISSUE TITLE
Please could we have this feature?

### ISSUE THREAD

**Issue by AubreyKloppers** [project-owner/Peppy#19]
Good morning
I am not sure where to ask this, but is it not possible to create a screensaver that will display a web-page?

Sorry, but I can not find a forum where to post this
kind regards
cyber7 (aka Aubrey Kloppers - Cape Town, South Africa)

**Comment by project-owner** [comment]
Hi Aubrey,

Where do you want to display a web-page? Should it be a touchscreen connected to the Pi or your Web Browser running somewhere else? In the former case this is problematic as that assumes running browser with framebuffer video output as the whole player UI is using framebuffer. Even if that's doable I suspect that's a lot of work.

Do you need to display some public web-page? Can it be useful for other users? Probably that web site supports some public API which could be used to get data. Then player could render/show that data in any way you want.

You can post your bug reports and feature requests here. You can also use the following forums:
Raspberry Pi (German). This is the most active forum: https://forum-raspberrypi.de/forum/thread/38115-peppy-webradio/?pageNo=1
Raspberry Pi: https://forums.raspberrypi.com/viewtopic.php?t=139983
DIY Audio: https://www.diyaudio.com/community/threads/peppy-player.288412/page-17#post-7014243

Best regards
