### ISSUE TITLE
Test internet connection with DNS

### ISSUE THREAD

**Issue by chrkoe** [project-owner/Peppy#20]
Hi,
today I set up my first Peppy and ran into an issue with internet connectivity detection. I found in peppy.py that you are testing it with google dns (8.8.8.8) which is blocked in my network.
It would be nice if that would be configurable by config.txt or it will just use the dns servers configured on the nic.

Greetings

**Comment by project-owner** [comment]
Hi,

What is your proposal? What should be defined in the config.txt? Should it be DNS server IP and port (Google by default)?

Thanks!

**Comment by chrkoe** [comment]
Hi,
I have no idea which block fits best. Maybe `[usage]`? But I thought of something like:
```
usecustomdns = True
customdns = 192.168.1.150
```
And default values would be:
```
usecustomdns = False
customdns = 8.8.8.8
```
Peppy could first check the `usecustomdns` value and if true it uses the `customdns` value insteaf of hard configured Google DNS (8.8.8.8)

**Comment by project-owner** [comment]
OK, how about just one property (empty by default):
```
custom.dns.ip = 
```
If it's empty use Google's 8.8.8.8 (with default port 53). If not empty use the IP from the property with the same default port 53.
Another way is the property:
```
dns.ip = 8.8.8.8
```
This way it's visible which IP is used for checking the Internet connection.

**Comment by chrkoe** [comment]
Hm, both sounds good. 👍 
choose whats lowest work for you 😉

**Comment by project-owner** [comment]
OK, I'll implement that in the next release.
Thanks!
