### ISSUE TITLE
Peppy exits without error

### ISSUE THREAD

**Issue by thomaswu0613** [project-owner/Peppy#23]
Hello,

I came across peppy player when I wondering what to do with my pi, but after installing peppy player it shows 'cannot import name 'collections_abc' from 'six.moves' (unknown location)', so I installed the six package through pip using python3 -m pip install six. After that I tried to run peppy with 'python3 peppy.py' then the program exits automatically after flashing a black pygame window without error as in the screenshot I attached. Please help, Thanks !

PS : I am using the raspberry pi legacy os image

![image](https://user-images.githubusercontent.com/43834693/182162456-53fca2d2-9a2c-47f9-8d53-eac0e2bea920.png)

**Comment by project-owner** [comment]
Hi,

I hope you followed the installation instructions. Please make sure that you installed all Peppy dependencies:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#installing-peppy-player-dependencies

You can enable console logging to see the program output:
https://github.com/project-owner/Peppy/blob/6284886bb1dfa0df556926826f8b1b2dcf6ad9fd/config.txt#L34
That should help to understand why it's failing.

Best regards

**Comment by thomaswu0613** [comment]
Thank you for your quick response. I have followed your advice and enabled the console logging option. Then I saw an error:
'[2022-08-02 10:59:59,480] {switchutil.py:47} ERROR - SMBus error'

I have searched for solutions but there's no luck in solving the error.

**Comment by project-owner** [comment]
That's OK to have that error if you don't use I2C bus. Here are all expected messages during player startup:
```
Hello from the pygame community. https://www.pygame.org/contribute.html
[2022-08-01 20:55:27,623] {switchutil.py:47} ERROR - SMBus error
[2022-08-01 20:55:27,655] {switchutil.py:56} DEBUG - 'switch'
[2022-08-01 20:55:31,506] {selector_events.py:53} DEBUG - Using selector: SelectSelector
[2022-08-01 20:55:31,629] {webserver.py:194} DEBUG - Web Server Started
[2022-08-01 20:55:32,386] {peppy.py:388} DEBUG - Audio Server Started
[2022-08-01 20:55:32,532] {collector.py:121} DEBUG - Collection database  not found
[2022-08-01 20:56:34,669] {util.py:1112} DEBUG - No script name
```
Have you installed VLC and VLC Python bindings? Here are the instructions:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#install-vlc-and-vlc-python-bindings

**Comment by thomaswu0613** [comment]
Oh silly me, I just forget to install the vlc-python blinding, Thank you!

**Comment by project-owner** [comment]
OK, I hope it works now. To avoid the whole system shutdown when you click on the Shutdown button in UI you need to set this property to True:
https://github.com/project-owner/Peppy/blob/6284886bb1dfa0df556926826f8b1b2dcf6ad9fd/config.txt#L25

**Comment by thomaswu0613** [comment]
Ok, thanks for your kind replay, I will close this issue now.
