### ISSUE TITLE
Peppy fails to start after system update

### ISSUE THREAD

**Issue by DrTron** [project-owner/Peppy#24]
All,

After getting Peppy set up and running great (installed from the Cezanne iso), I decided to update the Debian packages. After that, the OS still runs fine, however Peppy fails to start and only displays the startup screen.

I can see no python tasks running at all, nor any openvt ones. Setting file logging in config.txt does not result in a logfile. So it seems that the task just dies rather early. If the startup screen is independent of the peppy.py and coded into the OS, it might even not start at all. The corresponding line is present in rc.local.
When I try to run "openvt -s -- python3 peppy.py" from a ssh shell as user "pi" (the Raspi is "headless" with just a TFT display attached), that gives me a "permission denied" for the tty.

What groups does the "pi" user need to be in? I doubt that changed with the Raspberry OS update, but maybe it was.
Are there any python package versions where incompatibilities are known to exist?

Thanks!

**Comment by project-owner** [comment]
Hi,

The disk images have OS patches which fix touchscreen and ALSA issues:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#patch-alsa-library
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#install-patched-libsdl12
By updating OS you remove those patches. Probably some other changes happen during update as well.

The player's splash screen starts independently from player. So you are right - you can see the splash screen but the player probably cannot start.

So, I would not recommend to update OS. If you still want to debug the best way is to use the Headless mode (set to True):
https://github.com/project-owner/Peppy/blob/6284886bb1dfa0df556926826f8b1b2dcf6ad9fd/config.txt#L20
After that you should not see that 'permission denied' message. You can connect to the player (if it starts) using web browser.
When you prove that it works in the headless mode you can try to switch to the touchscreen.

Best regards

**Comment by DrTron** [comment]
Thanks, I wasn't aware you had to patch that much in the images to get it working.
I personally like to keep my systems up-to-date, especially in regard to security patches, but for a music player I can see that the importance of that is probably not all that high. I'll see if I can get those changes in (might just be the udev permissions for tty), if not I probably have to start from scratch and restore the Peppy folder backup.

Would you think it to be a good idea to include some kind of warning not to update the system here: https://github.com/project-owner/Peppy.doc/wiki/Updating-Guide or maybe some other more prominent place? I did not see any warning regarding that.

**Comment by project-owner** [comment]
I totally agree that it's better to keep OS up-to-date. Unfortunately it doesn't work all the time. My last attempt to move OS from Buster to the latest Bullseye failed. I was not able to make SPI touchscreens working there.

Actually I know some people succeeded updating OS after disk image installation. Though I don't know the details. I didn't investigate why it stops working after OS update. Please let me know if you will find the reason.

I added warning about OS update on that page.

**Comment by DrTron** [comment]
Ok, so for the solution:
The reason Peppy couldn't start was the permissions of the tty. After I fixed that, it's working fine again.
In the headless wiki, there is the instruction to have udev modify the permissions from 0620 to 0660, giving the tty group read rights on the tty. However, that is done in "/lib/udev/rules.d/50-udev-default.rules", where the first line actually tells you that it's going to get overwritten during updates.
My solution now is to create a new rules file in "/etc/udev/rules.d" with a number higher than 50. These files also get sourced by udev and as it's a higher number it gets processed later, overwriting the original "0620". Plus, these don't get overwritten on updates.

**Comment by project-owner** [comment]
Cool! I'll try to do that next time when I'll prepare new disk images.
Thanks!

**Comment by DrTron** [comment]
You're welcome, glad to help
Also, one might start Peppy from a systemd file instead of rc.local. A bit more elegant, and able to stop and restart if necessary (after config.txt changes, for instance).
I think I can puzzle one together...

**Comment by project-owner** [comment]
The splash screen starts using systemd. Long time ago I tried to start the player using systemd but I gave up by that time.

**Comment by DrTron** [comment]
I'll have a look.
In the meantime, I noticed that system load is quite high at 0.7 even when Peppy is idle and not playing. That's likely pygame doing that, but I wanted to mention it.
