### ISSUE TITLE
How to install custom touchscreen driver?

### ISSUE THREAD

**Issue by thomaswu0613** [project-owner/Peppy#25]
Sorry, it's me again. I saw there are different img files for different types of the touchscreen. However, I have a 3.5-inch touch screen which did not work with the img files the release provided. I did try the images with 3.5-inch touchscreen support but none of them worked. (The waveshare one worked with strange colour and the adafurit doesn't work at all.) So I end up installing the headless image and followed [this link](https://github-wiki-see.page/m/project-owner/PeppyPlayers.doc/wiki/Waveshare-3.5-%28B%29) to install my custom touch screen driver. The result is the console keeps showing but the peppy player UI flashes through the screen sometimes. Thank you!

**Comment by project-owner** [comment]
Hi, probably this will help:
https://github.com/project-owner/Peppy/issues/8

**Comment by thomaswu0613** [comment]
Ok thanks I will check that out 😄

**Comment by thomaswu0613** [comment]
Hello, the issue you provided solves the issue, Thanks!
