### ISSUE TITLE
GUI volume slider freeze

### ISSUE THREAD

**Issue by jsaarane** [project-owner/Peppy#27]
I have a bluetooth speaker connected to the player. Normally when using the radio everything works fine. Also if I use AirPlay everyhting works fine and I'm able to control the volume. The weird thing is when I use the radio after using AirPlay the volume is "stuck" it won't update. I need to adjust the slider and change the channel and then it will update the volume to the desired level.

**Comment by project-owner** [comment]
Hi, 

More likely you found a bug. I'll try to address it in the next release. 

Thank you!

**Comment by project-owner** [comment]
The issue was fixed in the new release - Seurat Edition.
