### ISSUE TITLE
Playback from a collection

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy#31]
I could not play music that is nested into more than one folder.
Eg.
\\ OMV \ MUZIKA \ Black Sabbath \ Paranoid \ is not working
![kolekce nejde](https://user-images.githubusercontent.com/35656251/225446203-1c303384-8c7e-458c-90bb-8d5dcd1a67a7.png)

\\ omv \ music \ bruce dickinson this is going
![kolekce jde](https://user-images.githubusercontent.com/35656251/225446237-868d77c1-9b26-48fa-8b24-83d41b7eec6f.png)

The collection is created, when walking in Peppy I know the individual songs, but in an attempt to play the message "File not found" will appear. I don't know if there is any restriction or need to set something somewhere

**Comment by project-owner** [comment]
Hi,

You have a talent - finding bugs :) There was a bug related to a back and forward slashes. You can get the fix this way:
```
cd Peppy
git fetch
git checkout origin/master -- ui/screen/topicdetail.py
```
Please let me know if it works now.
Thank you!
