### ISSUE TITLE
Alow to play spotify/airplay to bluetooth speaker

### ISSUE THREAD

**Issue by komw** [project-owner/Peppy#35]
Currently only the local files/radios are able to play via bluetooth. Spotify/Airplay still uses the local alsa device to play music.
Would be great if it will be able to play spotify/airplay via bluetooth.

**Comment by project-owner** [comment]
Hi, 

It should work. Here are the steps:
- Enable BT (in Usage)
- Enable Airplay (in Home Menu)
- Change the current ALSA output device to the 'default' in the Shairport-sync (used for Airplay) configuration file /etc/shairport-sync.conf. So, instead the current: output_device = "hw:Headphones"; specify: output_device = "default";
- Reboot (or even better shutdown/power on).

Airplay mode should work with BT device after that.

Best regards

**Comment by komw** [comment]
Thx!
