### ISSUE TITLE
vu meter and spectrum  do not display 

### ISSUE THREAD

**Issue by renbek** [project-owner/Peppy#36]
the vu meter, as well as the spectrum do not display anything, they remain at 0 all the time, I used the "klimt edition waveshare 5.0" image disk for the installation. everything else works perfectly, can you help me?

**Comment by project-owner** [comment]
Hi,

Did you make any changes after starting the player?
How do you output sound? Do you use onboard audio with output through audio jack or DAC or amplifier? Is sound OK?
Do you really use Waveshare 5" HDMI touchscreen or some clone?

Best regards

**Comment by renbek** [comment]
For the sound I use the headphones sound card [bcm 2835 headphones] connected via bluetooth I have not changed anything in the system parameters, the screen is the waveshare 5.0 "touchscreen connection DSI it is not a clone, the sound is excellent, everything works very well, except the VU meter and the spectrum which remains at 0
I hope you understand, I use "google translate", thank you for your help

**Comment by project-owner** [comment]
That's currently not supported. The player is using this ALSA audio configuration template (/home/pi/.asoundrc) for Bluetooth:
https://github.com/project-owner/Peppy/blob/0655be5202ecfef5de712ca4953353a47556b26b/util/bluetoothutil.py#L58

That configuration doesn't have the output for 'peppyalsa' device which is required for VU Meter and Spectrum working. That output looks like this:
https://github.com/project-owner/Peppy.doc/blob/9590567f7a2b87757bbbdafabd53caf13548d982/files/alsa-config/.asoundrc-equal-peppyalsa#L27

So, to make it working the 'peppyalsa' output should be added to the file .asoundrc file used for Bluetooth. You can try that, though that's not so trivial task.

Best regards

**Comment by renbek** [comment]
I thank you for your help, but this is a little ..., even too complex for me ;-), I am new to this field, I will stay on the configuration of the disk image while waiting for possible adaptations

**Comment by project-owner** [comment]
I've asked this question here:
https://www.diyaudio.com/community/threads/peppy-player.288412/post-7404831
Hopefully the ALSA experts there can help to create a correct configuration file.

**Comment by renbek** [comment]
I will follow this lead, again a big thank you for your help. It's a great project, I hope I have raised a problem that will delight many users
