### ISSUE TITLE
equalizer via bluetooth

### ISSUE THREAD

**Issue by AlexPtushkin** [project-owner/Peppy#37]
Good afternoon, I can not set up the equalizer via bluetooth. Please help. Changing the volume works, commands seem to be issued. The color of the sound does not change.

[vlc.linux]
server.start.command = --aout=alsa --alsa-audio-device=my-bluealsa-device --verbose=-1
client.name=vlcclient
stream.server.parameters = sout=#transcode{acodec=flac}:std{access=http,mux=flac,dst=:8080}
server.stop.command = None

pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw card 0
}
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm "my-bluealsa-device";
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}
pcm.my-bluealsa-device {
    type plug
    slave.pcm {
        type bluealsa
        device "41:42:C4:33:46:32"
        profile "a2dp"
        delay -20000
    }
}

**Comment by project-owner** [comment]
Hi,

I've tested equalizer with Bluetooth device and it woked fine.
There is no need to change the properties manually. 
Please use the 'default' device in the players.txt file:
```
server.start.command = --aout=alsa --alsa-audio-device=default --verbose=-1
```
and this /home/pi/.asoundrc file should work for your Bluetooth device:
```
pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw card 0
}
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm bt
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}
pcm.bt {
    type plug
    slave.pcm {
        type bluealsa
        device "41:42:C4:33:46:32"
        profile "a2dp"
        delay -20000
    }
}
```

Best regards

**Comment by AlexPtushkin** [comment]
Good afternoon dear friend! 
Yes, everything worked! Thanks for the help!
