### ISSUE TITLE
Screensavers weather

### ISSUE THREAD

**Issue by AlexPtushkin** [project-owner/Peppy#39]
Good afternoon, dear friend!
When displaying the weather on the screen, is it possible to indicate the wind speed in meters/sec, the pressure taking into account the height in mm. Mercury column? The OpenWeather server provides this data.
Thank you.

**Comment by AlexPtushkin** [comment]
![photo_2023-09-20_13-16-13](https://github.com/project-owner/Peppy/assets/51452581/ef735bf9-2b98-4d53-b317-47689fb1af23)

**Comment by AlexPtushkin** [comment]
![Screenshot_3](https://github.com/project-owner/Peppy/assets/51452581/905c1f91-32fe-4994-9f6f-c96f655fd95f)

**Comment by project-owner** [comment]
Hi,

To display a wind in meters you need to swicth units from F to C. The label will be still 'mph' though. That's probably confusing.
A pressure is not included to the UI at the moment.

Best regards

**Comment by AlexPtushkin** [comment]
I'm understood, thank you
