### ISSUE TITLE
Screensavers random

### ISSUE THREAD

**Issue by AlexPtushkin** [project-owner/Peppy#40]
Good afternoon, dear friend!
Enabled random switching of screensaver applications. I left the clock, logo, weather. After a minute, the image becomes muted and pictures are not displayed. What’s wrong?
![Screenshot_4](https://github.com/project-owner/Peppy/assets/51452581/a8c7c616-5ec3-407f-917c-56d1698d635c)
![Screenshot_5](https://github.com/project-owner/Peppy/assets/51452581/d35077b4-fdf4-470a-924f-483c235bfdbd)

**Comment by project-owner** [comment]
Hi,

That could happen if there was a switch between songs and the current album art was not avaialble yet. After 20 seconds it should switch to another screensaver.
Does it happen every time?

Best regards

**Comment by AlexPtushkin** [comment]
Good afternoon,
I removed the logo, left the clock and weather. After 1 minute the screen goes dark and the information no longer changes.

**Comment by AlexPtushkin** [comment]
If you take the logo, the clock, the weather separately, everything works. doesn't want to work randomly

**Comment by project-owner** [comment]
OK, I guess you are talking about Web UI. It works as expected because user can include screensavers which are not supported in a  Web UI (VU Meter and Spectrum). It currently doesn't check which screensavers have been included into the random one. Maybe I'll add that check in the next release.

Best regards

**Comment by AlexPtushkin** [comment]
Good morning,
I'm expecting a screen any day now, thanks for the clarification
Best regards
