### ISSUE TITLE
Blank page for Web based configuration System Tab

### ISSUE THREAD

**Issue by dadr** [project-owner/Peppy#46]
Hi,
I opened a new issue about this, because I did a fresh install using the `kandinsky-official.7.0.img.xz` image - and I still have the problem.

I have a Pi4B with 1G RAM and the following MIPI DSI screen: 
https://www.temu.com/goods_snapshot.html?goods_id=601099516772050
SanDisk High Endurance 32G uSD
USB Hub with charging outlets.  USB C charging cable direct to RPi

The following is exactly what I have done, nothing more, nothing left out.
```
Used balena etcher to burn the image to uSD.  The card has seen little use.

Saw the splash screen twice  (maybe because it expanded the filesystem?)

logged in using ssh

Changed pw using passwd

set Wi-Fi country, Eastern Time zone, US locale using raspi-config

edited /boot/config.txt: 
      commented out rotate display line,   (else the touch encoder is 180 out)
      commented out dtparam=audio=on, 
      added dtoverlay=hifiberry-dacplus

sudo reboot  - this did not work, it either hung or shutdown.   Power cycled.

Went to Peppy Config URL and tried System tab - no result.

edited [volume.control] as per https://github.com/project-owner/Peppy.doc/wiki/HiFiBerry-Amp
(By the way this page needs an update for the directory of the config file - about half way down)

sudo reboot -f   (this does work)

Radio stations now play properly, but still no joy on the System tab

I tried to reset browser history, nothing.  Tried Safari, Edge, Firefox on different computers, still no System tab.

I tried swapping between WiFi and Ethernet Cable, same results with either.  

Tried Raspberry Pi 3A power supply, no difference.

Turned on logging again (from Web config) and saw the same results that I have shared before.

```
It's a real head-scratcher.   I could swear I have seen that page before.

**Comment by project-owner** [comment]
Hi, is it possible to do the same but one step at a time and checking the availability of the System tab after each step? That can help to find out the root cause of the issue. So, first just install image on SD, insert into Pi and wait until UI shows up. Then check that System tab is available in the Configuration Web UI and so on.
Thank you!

**Comment by dadr** [comment]
With a red face - I've re-installed 3 more times with the exact same procedure.   In each case everything worked just fine.

One small nit - the VU meters and spectrum screensavers in the Official 7" distro come set to medium instead of large.

**Comment by project-owner** [comment]
Good to know that it works.
Argh, forgot to change the screensaver sizes for 7" display. I'll fix that today. Thank you!
