### ISSUE TITLE
screen saver freezes the touch screen

### ISSUE THREAD

**Issue by henkkoorn** [project-owner/Peppy#50]
Hello, I have been a peppy user for a few weeks now
but the touch screen no longer works when I use the screen saver
with the phone or laptop, I use a raspberry 3B and a 7" screen
I used Kandinsky image
this is my log file:
[2023-12-30 11:08:59,654] {amixerutil.py:44} DEBUG - ALSA mixer name: Headphone
[2023-12-30 11:08:59,789] {diskmanager.py:287} DEBUG - Started USB drive plug/unplug observer
[2023-12-30 11:09:00,729] {screensaverdispatcher.py:219} DEBUG - Get screensaver logo
[2023-12-30 11:09:00,763] {selector_events.py:53} DEBUG - Using selector: EpollSelector
[2023-12-30 11:09:00,780] {webserver.py:209} DEBUG - Web Server Started
[2023-12-30 11:09:01,067] {peppy.py:419} DEBUG - Audio Server Started
[2023-12-30 11:59:25,512] {util.py:1135} DEBUG - No script name
[2023-12-30 12:09:49,804] {util.py:1135} DEBUG - No script name
[2023-12-30 12:12:01,279] {util.py:1135} DEBUG - No script name
[2023-12-30 12:17:53,084] {web.py:2243} INFO - 200 GET / (192.168.2.8) 7.09ms
[2023-12-30 12:17:53,142] {web.py:2243} INFO - 304 GET /fonts?current (192.168.2.8) 4.35ms
[2023-12-30 12:17:53,191] {web.py:2243} INFO - 101 GET /ws (192.168.2.8) 3.65ms
[2023-12-30 12:17:53,192] {websockethandler.py:42} DEBUG - Added web client
[2023-12-30 12:18:50,234] {util.py:1135} DEBUG - No script name
[2023-12-30 12:19:38,723] {websockethandler.py:55} DEBUG - Removed web client
[2023-12-30 12:21:35,825] {util.py:1135} DEBUG - No script name

would you like to help me? thank you in advance
Sincerely

**Comment by project-owner** [comment]
Hi,

Which screensaver do you use? Does it happen when a screensaver starts the first time? Does it happen if you don't use phone or any other device? Have you tried to use a different screensaver? If so, does the same issue occur?
Your answers will help to identify the issue. Thanks!

Best regards

**Comment by henkkoorn** [comment]
Okay, I'm going to try again, but now with my laptop and phone turned off
in the menu clock, logo, weather and pexels set the delay to 1 min
tested all four and now everything is okay
has something to do with the telephone or laptop
to be continued

**Comment by henkkoorn** [comment]
the log file from above, screen saver on logo was selected and the phone was on
same problem with the screensaver clock, weather and pexels
I tested it again and the touchscreen doesn't work. now I have to restart to get it right
met vriendelijke groet

**Comment by project-owner** [comment]
I couldn't reproduce the issue with Raspberry Pi 3 and the Official Raspberry 7" Touchscreen. Which display and disk image do you use?
Do you use the 'Random' screensaver or separate savers? If the former, try to exclude the 'Pexels' saver and see if the issue still persists.

Best regards

**Comment by henkkoorn** [comment]
I use : 
- 7 inch dsi connector tft lcd-scherm capacitieve touchscreen
- kandinsky-official.7.0.img
- aparte savers clock or logo 
- touch screen and sometimes an iPhone (192.168.2.215:8000) to select the volume or another radio station
- the laptop (192.168.2.215:8000/config/ ) to adjust the configuration

**Comment by project-owner** [comment]
OK, I need minimum steps to reproduce the issue.

I installed Kandinsky Edition for Official 7" display on Raspberry Pi 3.
I connected from my desktop to Raspberry Pi and tried to use Clock and Logo screensavers. It worked fine.
Started Radio and waited 1 min for Clock screensaver. It worked fine.

I'm using wired connection. Do you use wired or wi-fi connection?

Best regards

**Comment by henkkoorn** [comment]
iI'm using wired connection.
then change the radio station or volume with your phone (always check the touch screen to see if it still works)
and after a few times the screen is dead
be patient
fijne oudejaars avond

**Comment by project-owner** [comment]
Hmm, I'm also using wired connection. I kept it running for about 4 hours (with Clock screensaver) from time to time changing radio stations and volume from my desktop and from the touchscreen. Haven't faced any issues...
To fix the issue I need to reproduce it first.

Best regards

**Comment by henkkoorn** [comment]
Hi, I understand that.
What language do you use? Dutch ?
I have now switched to English and it seems better. I do not understand that !
test it some more.

I have seen something else when I use the screen saver logo and I change the radio station then I see the logo of the previously selected radio station. do you know ?
Sincerely

**Comment by project-owner** [comment]
Hi, everything can make a difference. So, let me try to use Dutch. Which radio stations do you use? Did you make any configuration changes? I need all steps from a Pi start till the moment when it hangs.

I'll check that issue with logo. That's probably a bug.

Best regards

**Comment by henkkoorn** [comment]
radio station :  pop sky-radio
i use hifiberry-dac , i  change /boot/config.txt 
see https://www.michaelplaza.nl/pagina?function=open&id=216&readonly=1

**Comment by project-owner** [comment]
I was switching between 'Sky Radio' and 'Radio 10' and changing volume during 1.5 hours. I didn't see any issue.
I think the only difference between our systems now is the HifiBerry DAC. Is it possible to use the onboard audio system without DAC just to eliminate one varable from this equation?

Best regards

**Comment by henkkoorn** [comment]
Hi, I did that, unfortunately it doesn't help
If I restart in the configuration screen, it doesn't go away either
When I look in the terminal window with the command htop I see that all peppy processes stop and start again
Can I stop and restart more processes?
I really need to do a reboot before it's over
I don't know how to restart something so that the touch screen works again
maybe it's a hardware problem
maybe the LCD screen
I don't know and a bit expensive to buy a new LCD screen now
I'm going to try another application to test what's broken

Thank you very much for all the effort you have done for me
I think the Peppy project is a beautiful project, so beautifully made, my compliment
Sincerely

**Comment by project-owner** [comment]
The player works as a service. Therefore reboot from the config screen actually doesn't reboot the whole system, it just restarts the processes. That's why it's very fast.

The last idea which could help is to try another more powerful power supply. Actually this is the very first solution which is usually suggested in a Pi world :)

Thank you!
Good luck

**Comment by project-owner** [comment]
Please reopen if the issue is still there
