### ISSUE TITLE
Pipe is running but meters don't move

### ISSUE THREAD

**Issue by teacherguy2020** [project-owner/Peppy#51]
Today I installed PeppyMeter/peppyalsa on my raspberry pi 4. I am able to run VLC with output set to "peppyalsa" and I get sound through the headphone jack. I am also able to run cat /home.... and I can see the output of the pipe when playing music. So everything seems to be in place, but when I run PeppyMeter the needles do not move. I have confirmed the path to the pipe is correct, and I have checked the logs for PeppyMeter and see nothing unusual:

brianwis@raspberrypi:~/PeppyMeter $ python3 peppymeter.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
[2024-01-24 17:23:08,338] {datasource.py:102} DEBUG - opening pipe...
[2024-01-24 17:23:08,338] {datasource.py:124} DEBUG - starting data source...
[2024-01-24 17:23:08,339] {datasource.py:104} DEBUG - pipe opened
[2024-01-24 17:23:08,339] {datasource.py:119} DEBUG - pipe flushed
[2024-01-24 17:23:08,340] {datasource.py:133} DEBUG - data source started
[2024-01-24 17:23:08,341] {peppymeter.py:105} DEBUG - PeppyMeter initialized

I am attaching my config.txt, asound.conf (alsa), and around.conf (peppyalsa). I've changed the extensions so they would upload.

Thank you for your help.

[asound.conf.txt](https://github.com/project-owner/Peppy/files/14044948/asound.conf.txt)
[config.txt](https://github.com/project-owner/Peppy/files/14044949/config.txt)
[asoundalsa.conf.txt](https://github.com/project-owner/Peppy/files/14044950/asoundalsa.conf.txt)

**Comment by project-owner** [comment]
Hi, this is a place for the Peppy player issues not PeppyMeter. Anyway, the most important thing is that you can see data in the pipe (using cat or tail).

You need just one ALSA configuration file. It should be named .asoundrc (pay attention to the dot at the beginning) and it should be placed in your home directory /home/brianwis. Use the content from the file where you have 'meter_show 0' (asoundalsa.conf.txt)

Also the 'current' section in the PeppyMeter config.txt file should look like this:
```
[current]
meter = blue
random.meter.interval = 20
meter.size = wide
screen.width =
screen.height =
exit.on.touch = False
stop.display.on.touch = False
output.display = True
output.serial = False
output.i2c = False
output.pwm = False
output.http = False
use.logging = False
use.cache = True
frame.rate = 30
```

**Comment by teacherguy2020** [comment]
My apologies for mis-posting. Where should I go for follow up?

**Comment by project-owner** [comment]
I'm just one developer of two different projects: Peppy Player and PeppyMeter. You posted the PeppyMeter question in the Peppy player thread. That's OK, you can continue here.

**Comment by project-owner** [comment]
The workaround was found - using the disk image with pre-installed PeppyMeter:
https://github.com/project-owner/PeppyMeter/releases/tag/2023.01.21
