### ISSUE TITLE
Display shows only the home screen

### ISSUE THREAD

**Issue by henkkoorn** [project-owner/Peppy#55]
Display shows only the home screen.
I have a Rapberry 3B with a 7 inch touch screen. first I had kandinsky-official.7.0.img on it now picasso-waveshare.7.0.hdmi.img
but the display only shows the initial screen. everything else seems to work. can see via the web that the touch screen works 
would you like to help me?
Thank you very much in advance

**Comment by henkkoorn** [comment]
![IMG_0789](https://github.com/project-owner/Peppy/assets/41724474/785a0d3b-e59d-4300-a883-80a54c8a787c)

**Comment by project-owner** [comment]
Hi,

Which display do you have? Is it the official 7" display? Even though I don't have the disk image for this display some users reported that they were able to make working the disk image for the Waveshare 7" HDMI display with the official DSI display:
https://forums.raspberrypi.com/viewtopic.php?t=139983&start=500#p2218718

RIght now I'm trying to create a player version which will work with all display types (SPI, DSI and HDMI).

Best regards

**Comment by henkkoorn** [comment]
Hi,
I use 7 inch dsi connector tft lcd screen capacitive touchscreen 800x480
I don't know if it is an official DSI screen
kandinsky-official.7.0.img and kandinsky-waveshare.7.9.img also work
what can I do ?
Best regards

**Comment by project-owner** [comment]
Kandinsky and Picasso are very different versions. It was difficult to make all displays working with the latest OS. I would recommend to stay with Kandinsky if it works fine for you. I hope the next version will support all displays and disk images for all of them will be avaialble.

**Comment by henkkoorn** [comment]
Hi, I see they are different versions.
Too bad I have to stick with Kandinsky because Picasso has a very nice improvement, the "radio browser"
It is what it is
kind regards

**Comment by project-owner** [comment]
If you have a spare Raspberry Pi you could install the headless Picasso version and control it from a web browser running on any device in your home network.

**Comment by henkkoorn** [comment]
good idea, also a rasp. zero ?

**Comment by project-owner** [comment]
Sure, though I didn't try it myself. So, I don't guarantee that it will work, but you can try.
