### ISSUE TITLE
Trouble with dependencies

### ISSUE THREAD

**Issue by Hikari** [project-owner/Peppy#6]
I have trouble installing this app, because I am not sure which dependencies to install. It would be really awesome if you could provide a small install doc or maybe just a requirements.txt so pip knows what to do.

**Comment by project-owner** [comment]
I would recommend to use the Express method if you want to install the player on Raspberry Pi. To install on any other platform you can use the Expert method. Both methods have been described here:
https://github.com/project-owner/Peppy.doc/wiki/Installation-Guide
