### ISSUE TITLE
Network hangs on loading screen

### ISSUE THREAD

**Issue by kiam001** [project-owner/Peppy#7]

**Comment by project-owner** [comment]
Please provide more details:
- Does it happen every time?
- Do you use wired or Wi-Fi network?
- Which screen does it hang on? Is it splash screen or any other?
Thanks!

**Comment by kiam001** [comment]
I install Driver from my Wifi USB Stick tl-wn725n v2 from here http://downloads.fars-robotics.net/wifi-drivers/8188eu-drivers/

Works i edit wpa_supllicant
Works on debian from raspberry pi in gui (search and password and connect)
dont works choose in Peppy menu on network it hangs on loading...

Both tested
on preinstalled and self installed peppy

**Comment by project-owner** [comment]
OK, so it hangs when you are clicking on the Wi-Fi button on the Network screen.
Which Pi model do you use? If it's Pi3 or Pi4 did you try to use the on-board Wi-Fi? Does it work?
I hope after installing the player you also installed the driver for your Wi-Fi dongle.
Did you change anything in the wpa_supllicant file manually?

Could you enable the file logging by changing the following parameter to True?
https://github.com/project-owner/Peppy/blob/d9eb701c1f66be2ef5bccc8457bb96ece0f46f79/config.txt#L30
Then check if there is any error message in the log file /home/pi/Peppy/peppy.log when you click on the Wi-Fi button.

Thanks!

**Comment by kiam001** [comment]
Okay i send after i am Home logs

project-owner <notifications@github.com> schrieb am Do., 3. Dez. 2020,
18:55:

**Comment by kiam001** [comment]
> OK, so it hangs when you are clicking on the Wi-Fi button on the Network screen.
> Which Pi model do you use? If it's Pi3 or Pi4 did you try to use the on-board Wi-Fi? Does it work?
> I hope after installing the player you also installed the driver for your Wi-Fi dongle.
> Did you change anything in the wpa_supllicant file manually?
> 
> Could you enable the file logging by changing the following parameter to True?
> https://github.com/project-owner/Peppy/blob/d9eb701c1f66be2ef5bccc8457bb96ece0f46f79/config.txt#L30
> 
> 
> Then check if there is any error message in the log file /home/pi/Peppy/peppy.log when you click on the Wi-Fi button.
> Thanks!

I use Raspberry Pi 2 with no wifi chip, and use a external wifi stick
it hangs whan i click on Network menü from main menü

**Comment by project-owner** [comment]
Please feel free to reopen the issue whenever you have additional info.
