### ISSUE TITLE
Wrong (inverted?) colors for waveshare like 3.5" china screen

### ISSUE THREAD

**Issue by Kloppis** [project-owner/Peppy#8]
There seem to be a common problem with different versions of the waveshare 3.5" displays.
I just installed Peppy for the first time because it looks like it fits all my needs.
I got a Pi 3b+ and a chinese 3.5 inch display which exactly looks like a waveshare display.
So i used the image for 3.5" waveshare and all bootet up normally, display is working, touch is working, orientation is fine.
But the colors are way off. Looks like inverted or something.
A bit of google searching and i found a possible solution:
There are multiple drivers for these screens. I downloaded LCDshow from Github and used  ./LCD35-show to set another driver for the screen. After that i can not boot into Peppy anymore. I am stuck with the Peppy Bootlogo after a few lines of bootcode. But the boot logo looks normal now, without wrong colors, so the driver seems to be correct now.
I think it has something to do with the HDMI Framebuffer routing to the screen that is not working anymore.

Any advice, what to do to get it working?
It would also be a workaround for every single one of these waveshare like screens.

**Comment by project-owner** [comment]
Sometimes the driver installation program updates the file /etc/rc.local and removes the player startup code.
Please make sure that the following line is there:
su pi -c 'cd /home/pi/Peppy; openvt -s -- python3 peppy.py'
If not, add it to the file (use sudo) before the last 'exit 0' line
Also if you see in that file any line like '&fbcp' remove it.
Hopefully it helps.

**Comment by Kloppis** [comment]
Thanks for the answer, that did the trick.
i didnt notice that this install script is doing that in the rc.local.
very good to know. So Peppy is working with every of these screens.
Maybe there is a way to write an own script to switch between the display drivers without removing the startup code when using the premade image for these screens. Would be a nice feature to have.

Thnaks for your help and have a nice day.

**Comment by project-owner** [comment]
Yes, that would be great to have the script which could install different display drivers on top of the Headless image. Though it's difficult to cover all possible displays models. Recently I created wiki pages which describe the driver installation and configuration processes for different displays. I hope that will be helpful. For example this page for 3.5" display has that info about /etc/rc.local:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Waveshare-3.5-(B)
Happy Peppy!

**Comment by Fliwatt** [comment]
If I may add to this, I find the wiki entry about installing the new drivers a bit misleading. The wiki says 

> Then either comment out or remove three last lines in file /etc/rc.local starting from the line fbcp &. After that in the same file add the line which will start the player:

But my /etc/rc.local looked like this:
```

_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

sleep 7
fbcp &

con2fbmap 1 0

su pi -c 'cd /home/pi/Peppy; openvt -s -- python3 peppy.py'
exit 0
```
Commenting out the line with conf2bmap 1 0 broke Peppy, the UI was no longer displayed. However when I just commented out fbcp & everything worked perfectly as expected.

**Comment by project-owner** [comment]
Fliwatt, thank you for reporting the issue!
I updated the wiki page.
Please also read about the bug fix in the Hokusai Edition:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Known-Issues

Happy Peppy!
