### ISSUE TITLE
Issues with AirPlay and Spotify Connect

### ISSUE THREAD

**Issue by Schniitzelchen** [project-owner/Peppy#9]
Hi,

I run my Peppy Radio just by using the Headphonejack on my pi 3b.

When I Enable Airplay and Spotify Connect I don`t hear anything. If I change the settings from the services to hw:1 (Headphone Jack) I Hear some Music but then the Spectrum/VU-Meter Screensavers are not working and the equalizer isn't working either.

Can you help me, telling what I am doing wrong? I am running the latest Version of Peppy with the nearly default config for the Waveshare 5Inch Screen (Premade Image)

Thanks in advance

**Comment by project-owner** [comment]
Hi,

You can try to use the fix described here (Airplay Issue):
https://github.com/project-owner/PeppyPlayers.doc/wiki/Known-Issues#airplay-issue
I hope everything should work after that. 

Here is some additional information about equalizer:
https://github.com/mikebrady/shairport-sync/issues/1046
Hopefully it will be helpful.

Best regards

**Comment by DJayKay** [comment]
In the Meantime: Yes@a

**Comment by DJayKay** [comment]
In the Meantime Yes.
 Sound: OK 
Screensavers: not Working

**Comment by project-owner** [comment]
It's possible to make Equalizer and VU Meter working with Airplay by changing User and Group from 'shairport-sync' to 'pi' in two files:
/usr/lib/systemd/system/shairport-sync.service
```
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/local/bin/shairport-sync
User=pi
Group=pi

[Install]
WantedBy=multi-user.target
```
/etc/dbus-1/system.d/shairport-sync-dbus.conf
```
<!-- initial version, based on /etc/dbus-1/system.d/avahi-dbus.conf, with thanks -->
<!DOCTYPE busconfig PUBLIC
          "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
          "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- Allow users "root" and "shairport-sync" to own the Shairport Sync service -->
  <policy user="root">
    <allow own="org.gnome.ShairportSync"/>
  </policy>
  <policy user="pi">
    <allow own="org.gnome.ShairportSync"/>
  </policy>


  <!-- Allow anyone to invoke methods on Shairport Sync server -->
  <policy context="default">
    <allow send_destination="org.gnome.ShairportSync"/>
    <allow receive_sender="org.gnome.ShairportSync"/>
  </policy>

</busconfig>
```
The solution was found here:
https://github.com/mikebrady/shairport-sync/issues/1437
https://github.com/mikebrady/shairport-sync/issues/730
